@echo off
setlocal EnableExtensions
cd /d "%~dp0"
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" (
    echo [ERROR] vswhere.exe not found. Install Visual Studio Build Tools.
    exit /b 1
)
set "VSROOT="
for /f "usebackq tokens=*" %%I in (`"%VSWHERE%" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSROOT=%%I"
if not defined VSROOT (
    echo [ERROR] MSVC C++ tools not found. Add Desktop development with C++.
    exit /b 1
)
call "%VSROOT%\VC\Auxiliary\Build\vcvars64.bat" >nul
if errorlevel 1 exit /b 1
if not exist build mkdir build
pushd build
rem Keep target objects separate: LTCG app objects must not be overwritten by test builds.
for %%T in (app smoke balance curve wav) do if not exist obj\%%T mkdir obj\%%T
echo [1/4] Building AROGUE.exe...
rem App icon: src/arogue.ico is generated by tools/gen_icon.py; rc embeds it as resource 1.
rc /nologo /fo arogue.res ..\src\arogue.rc
if errorlevel 1 (popd & exit /b 1)
cl /nologo /Foobj\app\ /std:c++17 /O1 /Os /GL /Gw /Gy /MT /utf-8 /GR- /W4 /DUNICODE /D_UNICODE ..\src\campaign.cpp ..\src\main.cpp ..\src\screens.cpp ..\src\render.cpp ..\src\localization.cpp ..\src\audio.cpp ..\src\music.cpp ..\src\game.cpp arogue.res /Fe:AROGUE.exe /link /LTCG /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF user32.lib gdi32.lib winmm.lib
if errorlevel 1 (popd & exit /b 1)
copy /y ..\translations.tsv translations.tsv >nul
echo [2/4] Building and running deterministic smoke tests...
cl /nologo /Foobj\smoke\ /std:c++17 /O2 /MT /utf-8 /GR- /W4 ..\src\campaign.cpp ..\src\smoke.cpp ..\src\localization.cpp ..\src\game.cpp ..\src\music.cpp /Fe:smoke.exe /link /OPT:REF /OPT:ICF user32.lib
if errorlevel 1 (popd & exit /b 1)
.\smoke.exe
if errorlevel 1 (popd & exit /b 1)
echo [3/4] Running heuristic balance and curve samples...
cl /nologo /Foobj\balance\ /std:c++17 /O2 /MT /utf-8 /GR- ..\src\balance.cpp ..\src\game.cpp /Fe:balance.exe /link /OPT:REF /OPT:ICF user32.lib
if errorlevel 1 (popd & exit /b 1)
.\balance.exe
if errorlevel 1 (popd & exit /b 1)
cl /nologo /Foobj\curve\ /std:c++17 /O2 /MT /utf-8 /GR- /W4 ..\src\curve.cpp ..\src\game.cpp /Fe:curve.exe /link /OPT:REF /OPT:ICF user32.lib
if errorlevel 1 (popd & exit /b 1)
.\curve.exe
if errorlevel 1 (popd & exit /b 1)
rem BGM audition tool. Built only, never run here: wav.exe <outdir> writes drive_*.wav.
cl /nologo /Foobj\wav\ /std:c++17 /O2 /MT /utf-8 /GR- /W4 ..\src\wav.cpp ..\src\music.cpp /Fe:wav.exe /link /OPT:REF /OPT:ICF
if errorlevel 1 (popd & exit /b 1)
for %%A in (AROGUE.exe) do set "EXESIZE=%%~zA"
for %%A in (translations.tsv) do set "TRANSLATIONSIZE=%%~zA"
set /a PACKAGESIZE=EXESIZE+TRANSLATIONSIZE
rem The 1,474,560 byte floppy limit no longer fails the build. Still report the
rem size: knowing what ships is useful even when nothing depends on it.
echo [4/4] Package: %PACKAGESIZE% bytes ^(EXE %EXESIZE% + translations %TRANSLATIONSIZE%^)
popd
exit /b 0

