"""Generate compact, reviewed five-line story cards from the authored Markdown.

Run from any directory. --check verifies the checked-in header without writing.
No translation or gameplay state is inferred here; card ordering is explicit.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / 'docs' / 'A_ROGUE_스토리_기획.md'
OPTIONAL = ROOT / 'docs' / 'A_ROGUE_선택기록_대본.md'
OUTPUT = ROOT / 'src' / 'narrative_data.h'


def wide(value):
    return 'L"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"' if value else '0'


def card(title, path, stamp, lines):
    if not 1 <= len(lines) <= 5:
        raise ValueError(f'{title}: expected one to five lines')
    if any(len(line) > 64 for line in lines):
        raise ValueError(f'{title}: a line exceeds the story renderer budget')
    return ' {' + ', '.join(wide(x) for x in [title, path, stamp] + lines + [''] * (5 - len(lines))) + '}'


def generate():
    source = MAIN.read_text(encoding='utf-8-sig')
    pages = [m.group(1).splitlines() for m in re.finditer(r'~~~text\n(.*?)\n~~~', source, re.S)]
    if len(pages) != 46:
        raise ValueError(f'Expected 46 authored mandatory cards, got {len(pages)}')
    optional = []
    for section in re.split(r'(?m)^### ', OPTIONAL.read_text(encoding='utf-8-sig'))[1:]:
        title = section.splitlines()[0]
        path_match = re.search(r'기록 출처: `([^`]+)`', section)
        lines = re.findall(r'(?m)^> (.+)$', section)
        if path_match and lines:
            optional.append(card(title, path_match.group(1), 'OPTIONAL / READ ONLY', lines))
    if len(optional) != 21:
        raise ValueError(f'Expected 21 optional cards, got {len(optional)}')
    out = ['#pragma once', '// Generated by tools/generate_narrative.py. Edit the Markdown source.',
           '// 46 mandatory cards, 21 optional records; no old scenario text.', '']
    def array(name, entries, dims=''):
        out.append(f'static const StoryFragment {name}{dims or "[" + str(len(entries)) + "]"} = {{')
        out.append(',\n'.join(entries))
        out.extend(['};', ''])
    def single(name, entry):
        out.extend([f'static const StoryFragment {name} = {entry.strip()};', ''])
    intro = [card(f'P0{i+1} / ' + ['조력자', '판독과 실행', '여섯 볼륨'][i],
                  'ROGUE / FIRST CONTACT', 'CURRENT CONNECTION', pages[i]) for i in range(3)]
    array('NARRATIVE_INTRO_DATA', intro)
    single('STORY_INTRO_DATA', intro[0])
    single('STORY_RESUME_DATA', card('연결 복구', 'ROGUE / RECONNECT', 'SAME SESSION', [
        '로그: 연결을 다시 잡았어요.', '로그: 복구한 볼륨은 그대로예요.',
        '나는 전에 적어둔 이름을 확인한다.', '기록과 이번의 나는 계속 이어진다.', '남은 연결을 선택한다.']))
    single('STORY_RECOVERED_DATA', card('관리자 경로', 'A:\\ROGUE', '6 / 6 VERIFIED', [
        '여섯 볼륨의 연결이 모두 복구되었다.', 'ROGUE 안내창은 응답하지 않는다.',
        '남은 안내 기록: 실행은 당신이 결정하세요.', 'A:\\ROGUE에서 관리자 제어가 계속된다.', '나는 로그를 만나러 간다.']))
    bosses, shards = [], []
    for drive, letter in enumerate('CDENRX'):
        bosses.append(' {' + ',\n'.join(card(f'{letter}{floor+1} / 복구 기록',
            f'{letter}:\\RECOVERY\\BOSS_{floor+1}.LOG', 'VERIFIED / CURRENT RESPONSE', pages[3+drive*4+floor])
            for floor in range(3)) + '}')
        shards.append(card(f'{letter} / 연결 복구', f'{letter}:\\RECOVERY\\LINK.LOG',
            'VERIFICATION FRAGMENT', pages[6+drive*4]))
    bosses.append(' {' + ',\n'.join(card(['A1 / 같은 서명', 'A2 / 다른 선택', 'A3 / 남겨둔 경로'][i],
        'A:\\ROGUE\\SELF\\RESPONSE.LOG', 'CURRENT / ROGUE', pages[36+i]) for i in range(3)) + '}')
    array('STORY_BOSS_DATA', bosses, '[DRIVE_COUNT][3]')
    array('STORY_SHARD_DATA', shards)
    out += ['static const wchar_t* const STORY_SHARD_TEXT[6] = {',
        ' L"권한", L"기준 상태", L"귀환 연결", L"종료 요청", L"현재 기억", L"격리 정책"', '};', '']
    array('STORY_LOGS_DATA', [' {' + ',\n'.join(optional[d*3:d*3+3]) + '}' for d in range(7)], '[DRIVE_COUNT][3]')
    array('NARRATIVE_MILESTONE_DATA', [card(['S01 / 처음 느낀 통증', 'S02 / 좋아하는 수',
        'S03 / 보고하지 않은 문장', 'S04 / 서로 다른 끝', 'S05 / 무엇을 남길까',
        'S06-A / 원본', 'S06-B / 몇 번째', 'S06-C / 관리자 인계'][i],
        'ROGUE / PRIVATE CHANNEL', 'CURRENT RELATIONSHIP', pages[27+i]) for i in range(8)])
    single('NARRATIVE_A_ENTRY_DATA', card('A00 / 남은 안내', 'A:\\ROGUE', 'RECORDED VOICE', pages[35]))
    single('NARRATIVE_A_GREETING_DATA', card('LAST.WRITE / ROGUE', 'A:\\ROGUE\\SELF', 'USER AUTHENTICATION', [
        '같은 인증음. 같은 글자 침식.', '로그: 환영합니다. 마스터.', '나: 로그. 내 이름으로 불러.',
        '안내자의 윤곽이 관리자 얼굴에 겹친다.', '공격 경로는 아직 열려 있다.']))
    single('STORY_TRUTH_DATA', card('FINAL / 종료 조건', 'A:\\ROGUE\\CONSENT', 'CURRENT USER REQUIRED', pages[39]))
    endings = ['RESTORE / 다시 복구', 'HOLD / 현재 유지', 'EXIT / 현재로 종료']
    array('STORY_ENDING_DATA', [card(endings[i], 'A:\\ROGUE\\FINAL_COMMAND', 'CHOICE COMMITTED', pages[40+i*2]) for i in range(3)])
    array('NARRATIVE_ENDING_LAST_DATA', [card(endings[i], 'A:\\ROGUE\\AFTER', 'ENDING / 2', pages[41+i*2]) for i in range(3)])
    return '\n'.join(out)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8-sig') != data:
            raise SystemExit('narrative_data.h differs from the authored Markdown; regenerate it')
        print('Narrative checked: 46 mandatory cards + 21 optional records, 1-5 lines each.')
    else:
        OUTPUT.write_text(data, encoding='utf-8', newline='\n')
        print('Generated src/narrative_data.h (46 mandatory cards + 21 optional records).')
