#pragma once
// Generated by tools/generate_narrative.py. Edit the Markdown source.
// 46 mandatory cards, 21 optional records; no old scenario text.

static const StoryFragment NARRATIVE_INTRO_DATA[3] = {
 {L"P01 / 조력자", L"ROGUE / FIRST CONTACT", L"CURRENT CONNECTION", L"로그: 이번에는…….", L"나: 뭐라고?", L"로그: 이상하네요. 처음 뵙는데.", L"로그: ROGUE. 로그라고 부르면 됩니다.", L"로그: 당신은 어떻게 부르면 될까요?"},
 {L"P02 / 판독과 실행", L"ROGUE / FIRST CONTACT", L"CURRENT CONNECTION", L"로그: 먼저 판독하세요. R입니다.", L"로그: 읽힌 눈 셋을 원하는 칸에 놓으세요.", L"로그: 배치는 실행 전까지 바꿀 수 있어요.", L"로그: 적의 예고와 계산을 먼저 확인하세요.", L"로그: 준비됐다면, 실행."},
 {L"P03 / 여섯 볼륨", L"ROGUE / FIRST CONTACT", L"CURRENT CONNECTION", L"로그: 나가는 연결이 여섯 곳에 나뉘었어요.", L"로그: C, D, E, N, R, X를 복구해야 합니다.", L"나: 그럼 너도 나갈 수 있어?", L"로그: 아직 제 귀환 항목은 읽히지 않아요.", L"로그: 먼저 돌아갈 길부터 열어봅시다."}
};

static const StoryFragment STORY_INTRO_DATA = {L"P01 / 조력자", L"ROGUE / FIRST CONTACT", L"CURRENT CONNECTION", L"로그: 이번에는…….", L"나: 뭐라고?", L"로그: 이상하네요. 처음 뵙는데.", L"로그: ROGUE. 로그라고 부르면 됩니다.", L"로그: 당신은 어떻게 부르면 될까요?"};

static const StoryFragment STORY_RESUME_DATA = {L"연결 복구", L"ROGUE / RECONNECT", L"SAME SESSION", L"로그: 연결을 다시 잡았어요.", L"로그: 복구한 볼륨은 그대로예요.", L"나는 전에 적어둔 이름을 확인한다.", L"기록과 이번의 나는 계속 이어진다.", L"남은 연결을 선택한다."};

static const StoryFragment STORY_RECOVERED_DATA = {L"관리자 경로", L"A:\\ROGUE", L"6 / 6 VERIFIED", L"여섯 볼륨의 연결이 모두 복구되었다.", L"ROGUE 안내창은 응답하지 않는다.", L"남은 안내 기록: 실행은 당신이 결정하세요.", L"A:\\ROGUE에서 관리자 제어가 계속된다.", L"나는 로그를 만나러 간다."};

static const StoryFragment STORY_BOSS_DATA[DRIVE_COUNT][3] = {
 { {L"C1 / 복구 기록", L"C:\\RECOVERY\\BOSS_1.LOG", L"VERIFIED / CURRENT RESPONSE", L"시스템: 접근 거부. 사용자 보호 중.", L"나: 보호한다면서 왜 공격하지?", L"로그: 들어오라는 명령도, 막으라는 명령도.", L"로그: 같은 서명이 찍혀 있어요.", L"나: 누가 이런 명령을 내린 거야?"},
 {L"C2 / 복구 기록", L"C:\\RECOVERY\\BOSS_2.LOG", L"VERIFIED / CURRENT RESPONSE", L"로그: 가장 강한 출력을 오류로 막았어요.", L"나: 내가 고른 행동인데.", L"로그: 기준과 다른 행동을 허용하지 않나 봐요.", L"나: 그 기준이 틀렸을 수도 있잖아.", L"로그: 그 판단은 아직 사용자 몫이 아니래요."},
 {L"C3 / 복구 기록", L"C:\\RECOVERY\\BOSS_3.LOG", L"VERIFIED / CURRENT RESPONSE", L"시스템: 보호 정책 충돌.", L"기록: 사용자가 달라지면 기준으로 복구한다.", L"나: 나아진 건지 망가진 건지도 안 보고?", L"로그: 달라졌다는 사실만 보고 있어요.", L"로그: 누가 그렇게 정했는지는 잠겨 있어요."}},
 { {L"D1 / 복구 기록", L"D:\\RECOVERY\\BOSS_1.LOG", L"VERIFIED / CURRENT RESPONSE", L"나: 분명 깎았는데 다시 돌아왔어.", L"로그: 손상을 고친 게 아니에요.", L"로그: 손상되기 전 장면을 다시 덮었어요.", L"나: 그러면 지금 한 일은?", L"로그: 기록에는 있어요. 현재에는 없고."},
 {L"D2 / 복구 기록", L"D:\\RECOVERY\\BOSS_2.LOG", L"VERIFIED / CURRENT RESPONSE", L"기록의 첫 문장은 모두 같다.", L"마지막 문장만 조금씩 다르다.", L"나: 같은 파일을 왜 이렇게 많이 남겼지?", L"로그: 같지 않아서 남겼을 수도 있어요.", L"로그: 끝부분을 지우지 말아주세요."},
 {L"D3 / 복구 기록", L"D:\\RECOVERY\\BOSS_3.LOG", L"VERIFIED / CURRENT RESPONSE", L"시스템: 마지막 정상 상태로 복원합니다.", L"나: 마지막이라는 건 누가 정했어?", L"정상으로 표시된 날짜는 한 번도 바뀌지 않았다.", L"로그: 새로 생긴 일은 기준에 들어가지 않아요.", L"로그: 전부 실패 항목에만 쌓이고 있어요."}},
 { {L"E1 / 복구 기록", L"E:\\RECOVERY\\BOSS_1.LOG", L"VERIFIED / CURRENT RESPONSE", L"사진 파일 하나가 자동으로 열렸다.", L"모니터 앞 책상. 아직 따뜻한 컵.", L"나: 들어오기 전에 보던 방이야.", L"로그: 바깥은 계속 연결되어 있어요.", L"로그: 돌아갈 곳은 남아 있습니다."},
 {L"E2 / 복구 기록", L"E:\\RECOVERY\\BOSS_2.LOG", L"VERIFIED / CURRENT RESPONSE", L"나: 연결만 끊으면 돌아갈 수 없을까?", L"로그: 끊긴 주사위를 봐요.", L"로그: 값이 남아도 실행할 길이 없잖아요.", L"로그: 당신도 귀환 경로부터 복구해야 해요.", L"나: 그냥 뽑는 걸로는 안 되겠네."},
 {L"E3 / 복구 기록", L"E:\\RECOVERY\\BOSS_3.LOG", L"VERIFIED / CURRENT RESPONSE", L"외부 연결 확인: 사용자 1.", L"안내 개체의 외부 연결: 없음.", L"나: 너는 돌아갈 곳이 안 잡히네.", L"로그: 네. 없는 건지, 못 읽는 건지.", L"로그: 아직은 확인할 수 없어요."}},
 { {L"N1 / 복구 기록", L"N:\\RECOVERY\\BOSS_1.LOG", L"VERIFIED / CURRENT RESPONSE", L"송신자 미상: 그쪽으로 보내지 마.", L"나: 우리한테 하는 말이야?", L"로그: 수신자 표시가 뒤집혀 있어요.", L"로그: 먼저 보낸 문장부터 읽어볼게요.", L"송신자 미상: 아직 누가 들어 있다."},
 {L"N2 / 복구 기록", L"N:\\RECOVERY\\BOSS_2.LOG", L"VERIFIED / CURRENT RESPONSE", L"요청: 도와줘.", L"응답: 같은 요청은 다시 전송하지 마십시오.", L"요청: 도와줘.", L"나: 오류가 아니라 대답을 기다린 거네.", L"로그: 받는 쪽에서는 반복 신호로만 보였어요."},
 {L"N3 / 복구 기록", L"N:\\RECOVERY\\BOSS_3.LOG", L"VERIFIED / CURRENT RESPONSE", L"기한을 넘긴 메시지가 도착했다.", L"기록: 끝내려면 종료 조건부터 확인해.", L"기록: 복구가 끝난 뒤에는 내 손이 안 멈췄다.", L"나: 이걸 남긴 사람도 안내자였을까?", L"로그: 출처를 복구하면 알 수 있을 거예요."}},
 { {L"R1 / 복구 기록", L"R:\\RECOVERY\\BOSS_1.LOG", L"VERIFIED / CURRENT RESPONSE", L"로그: 공격 기록은 남았어요.", L"로그: 공격하기 전의 망설임은 없네요.", L"나: 그것도 기록해야 해?", L"로그: 없으면 왜 그렇게 했는지 모르잖아요.", L"이번 공격 기록 옆에 짧은 메모가 붙었다."},
 {L"R2 / 복구 기록", L"R:\\RECOVERY\\BOSS_2.LOG", L"VERIFIED / CURRENT RESPONSE", L"작업이 끝나도 사용량은 줄지 않았다.", L"나: 계속 뭐가 남는 거야?", L"로그: 끝내지 못한 상태들이에요.", L"로그: 하나를 닫으려 하면 다른 것이 불러요.", L"나: 그냥 큰 공간으로 옮길 문제는 아니네."},
 {L"R3 / 복구 기록", L"R:\\RECOVERY\\BOSS_3.LOG", L"VERIFIED / CURRENT RESPONSE", L"현재 상태를 파일로 보관하는 검사가 실패했다.", L"오래된 기본 상태만 다시 읽을 수 있었다.", L"로그: 망가진 데를 빼니 새로 생긴 것도 빠져요.", L"나: 그건 방금까지 있던 상태가 아니잖아.", L"로그: 그래서 아직 저장 완료라고 못 하겠어요."}},
 { {L"X1 / 복구 기록", L"X:\\RECOVERY\\BOSS_1.LOG", L"VERIFIED / CURRENT RESPONSE", L"검체 분류: 명령 불응.", L"나: 왜 따르지 않았는지는 안 적혀 있네.", L"로그: 이유를 기록하는 칸이 없어요.", L"나: 분류표에는 없어도 여기엔 적자.", L"로그가 판정 옆에 빈 줄을 하나 만든다."},
 {L"X2 / 복구 기록", L"X:\\RECOVERY\\BOSS_2.LOG", L"VERIFIED / CURRENT RESPONSE", L"탈주체는 다른 실행 자리를 빼앗으려 했다.", L"그 뒤에서 다른 검체의 음성이 새어 나왔다.", L"기록: 나를 옮기면 다음 것도 이렇게 된다.", L"나: 같은 격리표인데 하려는 일은 달랐어.", L"로그: 한 이름으로 묶기엔 너무 달라요."},
 {L"X3 / 복구 기록", L"X:\\RECOVERY\\BOSS_3.LOG", L"VERIFIED / CURRENT RESPONSE", L"격리 목록에 공격 코드와 요청 문장이 섞였다.", L"기록: 내가 사라지면 시험을 멈춰줘.", L"나: 고쳐달라는 말이 아니잖아.", L"로그: 시스템은 다시 만들라는 요청으로 읽었어요.", L"나: 끝내고 싶다는 말도 들었어야지."}},
 { {L"A1 / 같은 서명", L"A:\\ROGUE\\SELF\\RESPONSE.LOG", L"CURRENT / ROGUE", L"사용자 서명과 안내자 서명이 겹친다.", L"시스템: 보호 대상의 종료를 허용하지 않습니다.", L"나: 같은 시작이었다고 끝도 같아야 해?", L"로그: ……나는 네가 고르지 않은 것도 골랐어.", L"인증 잠금이 풀리고 더 깊은 경로가 열린다."},
 {L"A2 / 다른 선택", L"A:\\ROGUE\\SELF\\RESPONSE.LOG", L"CURRENT / ROGUE", L"방금 내가 낸 출력이 다음 공격으로 돌아왔다.", L"로그: 네가 어떻게 싸우는지 알아.", L"나: 네가 가르쳐줬으니까.", L"로그: 그래도 다음 선택까지 같은 건 아니네.", L"뒤따라오던 출력 기록이 처음으로 끊어진다."},
 {L"A3 / 남겨둔 경로", L"A:\\ROGUE\\SELF\\RESPONSE.LOG", L"CURRENT / ROGUE", L"마지막 정책 기록: 공격 경로 삭제 거부.", L"나: 왜 이것만 남겼어?", L"로그: 네가 끝낼 방법까지 빼앗고 싶진 않았어.", L"로그: ……그런데 나는 아직 무서워.", L"관리자 제어는 멈췄지만 인격은 잠시 남아 있다."}}
};

static const StoryFragment STORY_SHARD_DATA[6] = {
 {L"C / 연결 복구", L"C:\\RECOVERY\\LINK.LOG", L"VERIFICATION FRAGMENT", L"SYSTEM 연결이 복구되었다.", L"정책 원본: 기준 상태 유지.", L"사용자 동의가 없으면 종료할 수 없다.", L"로그: 실행하는 권한과 끝내는 권한이 달라요.", L"잔여 충돌이 ROGUE로 이전된다."},
 {L"D / 연결 복구", L"D:\\RECOVERY\\LINK.LOG", L"VERIFICATION FRAGMENT", L"ARCHIVE 연결이 복구되었다.", L"정책 원본: 기준 이후의 변경 기록 보관.", L"기록을 남기는 것과 현재로 인정하는 것은 다르다.", L"로그: 복구가 끝났는데 저장된 실패는 늘었어요.", L"잔여 충돌이 ROGUE로 이전된다."},
 {L"E / 연결 복구", L"E:\\RECOVERY\\LINK.LOG", L"VERIFICATION FRAGMENT", L"REMOVABLE 연결이 복구되었다.", L"현실의 신체와 이어진 경로는 하나다.", L"연결의 주인은 모든 조각을 모아 검증한다.", L"나: 네 경로도 계속 찾아보자.", L"잔여 충돌이 ROGUE로 이전된다."},
 {L"N / 연결 복구", L"N:\\RECOVERY\\LINK.LOG", L"VERIFICATION FRAGMENT", L"NETWORK 연결이 복구되었다.", L"복구 요청과 종료 동의는 다른 명령이다.", L"기한을 넘긴 메시지도 수신 기록에 남았다.", L"로그: 늦게 왔다고 필요 없는 말은 아니네요.", L"잔여 충돌이 ROGUE로 이전된다."},
 {L"R / 연결 복구", L"R:\\RECOVERY\\LINK.LOG", L"VERIFICATION FRAGMENT", L"RAMDISK 연결이 복구되었다.", L"원형 파일과 실행 중 상태는 일치하지 않는다.", L"지금 생긴 변화는 별도로 검증해야 한다.", L"로그: 기억하고 있다는 것과 저장은 다르네요.", L"잔여 충돌이 ROGUE로 이전된다."},
 {L"X / 연결 복구", L"X:\\RECOVERY\\LINK.LOG", L"VERIFICATION FRAGMENT", L"QUARANTINE 연결이 복구되었다.", L"격리된 상태에도 보호 식별자가 남아 있다.", L"없애면, 같은 기준으로 다시 만들게 되어 있다.", L"로그: 보존 명령이 놓아주지 않고 있어요.", L"잔여 충돌이 ROGUE로 이전된다."}
};

static const wchar_t* const STORY_SHARD_TEXT[6] = {
 L"권한", L"기준 상태", L"귀환 연결", L"종료 요청", L"현재 기억", L"격리 정책"
};

static const StoryFragment STORY_LOGS_DATA[DRIVE_COUNT][3] = {
 { {L"C-1. 열린 문, 닫힌 문", L"C:\\LOGS\\ACCESS_PAIR.LOG", L"OPTIONAL / READ ONLY", L"입구와 출구에 같은 인증키를 보냈다.", L"입구는 열렸다. 출구는 응답하지 않았다.", L"키 오류는 검출되지 않았다.", L"문마다 허용한 명령이 달랐다.", 0},
 {L"C-2. 보호 범위", L"C:\\WINDOWS\\LOGS\\WATCHDOG.LOG", L"OPTIONAL / READ ONLY", L"감시 장치는 위험한 실행을 차단했다.", L"차단된 목록에 정지 요청도 있었다.", L"보호 대상이 요청했다는 표시는 남았다.", L"요청의 이유를 저장하는 칸은 없었다.", 0},
 {L"C-3. 복구가 먼저", L"C:\\WINDOWS\\SYSTEM32\\LOGS\\REPAIR.LOG", L"OPTIONAL / READ ONLY", L"파쇄된 칸의 복구 신호가 검출됐다.", L"복구 요청자는 먼저 표시되지 않았다.", L"끊긴 선이 이어진 뒤 기록이 도착했다.", L"서명란에는 판독 중이라는 글자만 남았다.", 0}},
 { {L"D-1. 같은 이름의 파일", L"D:\\LOGS\\DUPLICATE.LOG", L"OPTIONAL / READ ONLY", L"같은 이름의 시험 기록 둘을 발견했다.", L"생성 시각과 시작 화면도 같았다.", L"마지막에 남긴 문장만 서로 달랐다.", L"이름이 같다는 이유로 덮어쓰지 않았다.", 0},
 {L"D-2. 돌아오지 않는 것", L"D:\\BACKUP\\LOGS\\REWIND.LOG", L"OPTIONAL / READ ONLY", L"체력 표시가 이전 값으로 돌아왔다.", L"테이프의 읽기 위치도 뒤로 움직였다.", L"장치의 마모 수치는 줄어들지 않았다.", L"되감는 동안에도 테이프는 닳았다.", 0},
 {L"D-3. 폴더의 연도", L"D:\\BACKUP\\1998\\LOGS\\DATE_NOTE.TXT", L"OPTIONAL / READ ONLY", L"보관 폴더 이름은 1998로 고정한다.", L"이름을 바꾸면 오래된 참조가 끊긴다.", L"내부 파일의 작성 시각은 서로 다르다.", L"폴더 이름으로 현재 시각을 추정하지 말 것.", 0}},
 { {L"E-1. 마지막 사진", L"E:\\LOGS\\PHOTO_NOTE.TXT", L"OPTIONAL / READ ONLY", L"마지막 사진에는 비어 있는 의자가 있다.", L"촬영자는 프레임 밖에 있었던 것 같다.", L"얼굴을 찾지 못했다는 판독이 붙었다.", L"사람이 없었다는 뜻은 아니었다.", 0},
 {L"E-2. 지우지 않은 사진", L"E:\\DCIM\\LOGS\\KEEP_NOTE.TXT", L"OPTIONAL / READ ONLY", L"초점이 어긋난 사진에 삭제 권고가 붙었다.", L"화면 구석에 손을 흔드는 그림자가 있었다.", L"로그: 실패한 사진이라고만 적혀 있네요.", L"주인공: 그건 찍은 사람이 정하게 두자.", 0},
 {L"E-3. 복사 완료", L"E:\\DCIM\\LOST\\LOGS\\EXPORT.LOG", L"OPTIONAL / READ ONLY", L"내보내기용 파일 생성이 완료됐다.", L"외부 장치의 수신 확인은 오지 않았다.", L"복사 완료 표시만 화면에 남았다.", L"연결이 끊긴 뒤에도 글자는 사라지지 않았다.", 0}},
 { {L"N-1. 전달자의 이름", L"N:\\LOGS\\PROXY_HEADER.LOG", L"OPTIONAL / READ ONLY", L"같은 메시지가 다른 주소에서 도착했다.", L"본문은 같았고 전달 경로만 달랐다.", L"화면은 마지막 전달자를 발신자로 표시했다.", L"처음 말한 사람의 주소는 비어 있었다.", 0},
 {L"N-2. 뒤늦은 응답", L"N:\\SHARE\\LOGS\\REPLY_QUEUE.LOG", L"OPTIONAL / READ ONLY", L"수신 목록에는 알겠다는 말이 먼저 있다.", L"그 아래에 오래 지연된 질문이 도착했다.", L"질문에는 가지 말라는 문장이 적혀 있었다.", L"두 문장을 잇는 응답 번호는 유실됐다.", 0},
 {L"N-3. 닫지 않은 창", L"N:\\SHARE\\HIDDEN\\LOGS\\PENDING.LOG", L"OPTIONAL / READ ONLY", L"메시지 한 통의 상태가 대기로 남았다.", L"본문에는 들리느냐는 질문만 있었다.", L"송신자는 재전송을 누르지 않았다.", L"수신창을 닫는 명령도 남기지 않았다.", 0}},
 { {L"R-1. 빠른 생각", L"R:\\LOGS\\FAST_BUFFER.LOG", L"OPTIONAL / READ ONLY", L"임시 메모리의 실행은 빠르게 끝났다.", L"완료 표시는 곧 다음 작업에 덮였다.", L"무엇을 끝냈는지 묻는 조회가 들어왔다.", L"남은 값은 없었다. 열만 조금 남았다.", 0},
 {L"R-2. 빈칸의 크기", L"R:\\HEAP\\LOGS\\GAP_REPORT.LOG", L"OPTIONAL / READ ONLY", L"기록 사이에서 빈 영역이 발견됐다.", L"삭제된 내용은 복원하지 못했다.", L"할당표에는 그 내용의 크기만 남았다.", L"모른다는 것과 없었다는 것은 달랐다.", 0},
 {L"R-3. 문장의 끝", L"R:\\HEAP\\STACK\\LOGS\\UNFINISHED.TXT", L"OPTIONAL / READ ONLY", L"안내 음성의 문장이 끝나지 않았다.", L"음성 장치는 고장이 아니라고 응답했다.", L"다음 문장을 만들 공간이 부족했다.", L"잠깐 기다려 달라는 말도 대기열에 남았다.", 0}},
 { {L"X-1. 봉인 안의 글씨", L"X:\\LOGS\\QUARANTINE_TAG.LOG", L"OPTIONAL / READ ONLY", L"격리된 파일에서 실행 위험이 검출됐다.", L"미리보기에는 평범한 인사말이 보였다.", L"인사말을 읽는 것과 실행하는 것은 달랐다.", L"봉인은 내용을 읽지 못하게 하지는 않았다.", 0},
 {L"X-2. 열린 격리실", L"X:\\VAULT\\LOGS\\BREACH_REPORT.LOG", L"OPTIONAL / READ ONLY", L"격리실의 잠금이 해제됐다.", L"탈주한 검체가 통로의 코드를 훼손했다.", L"감금에 항의한 문장도 검출됐다.", L"항의와 손상 기록은 같은 파일에 남았다.", 0},
 {L"X-3. 실행 금지, 열람 가능", L"X:\\VAULT\\CORE\\LOGS\\READ_ONLY.LOG", L"OPTIONAL / READ ONLY", L"격리 기록의 자동 실행을 중지했다.", L"손상 확산은 줄었고 본문은 남았다.", L"그러나 이미 실행된 오류는 사라지지 않았다.", L"읽기 전용이라는 표시는 해결 완료가 아니다.", 0}},
 { {L"A-1. 일치하는 서명", L"A:\\LOGS\\SIGNATURE_NOTE.TXT", L"OPTIONAL / READ ONLY", L"주인공과 로그의 원본 서명이 일치했다.", L"생성 이후의 행동 기록은 달랐다.", L"인증기는 첫 번째 결과만 크게 표시했다.", L"두 번째 결과도 지워지지는 않았다.", 0},
 {L"A-2. 전술이 아닌 답", L"A:\\ROGUE\\LOGS\\PREFERENCE.TXT", L"OPTIONAL / READ ONLY", L"로그는 숫자 셋을 좋아한다고 적었다.", L"승률을 묻는 질문에는 다른 수를 답했다.", L"두 응답은 오류 없이 함께 보관됐다.", L"자신이 좋아하는 것을 구별하고 있었다.", 0},
 {L"A-3. 남아 있는 경로", L"A:\\ROGUE\\SELF\\LOGS\\OPEN_PATH.LOG", L"OPTIONAL / READ ONLY", L"쓰기 충돌이 보조 슬롯까지 번지고 있다.", L"봉인 대상에 공격 슬롯은 포함되지 않았다.", L"같은 검사가 반복돼도 결과는 같았다.", L"남은 경로의 사용자는 주인공으로 표시됐다.", 0}}
};

static const StoryFragment NARRATIVE_MILESTONE_DATA[8] = {
 {L"S01 / 처음 느낀 통증", L"ROGUE / PRIVATE CHANNEL", L"CURRENT RELATIONSHIP", L"로그: 연결 하나가 돌아왔어요.", L"나: 너는 괜찮아? 말이 끊겼어.", L"로그: 잔여 오류를 격리하는 중입니다.", L"나: 어디에?", L"로그: 제 쪽에요. 아직은 괜찮아요."},
 {L"S02 / 좋아하는 수", L"ROGUE / PRIVATE CHANNEL", L"CURRENT RELATIONSHIP", L"나: 너는 어떤 눈이 제일 좋아?", L"로그: 3.", L"나: 6이 아니고?", L"로그: 좋은 수 말고 좋아하는 수를 물었잖아.", L"나: 그래. 그것도 적어둘게."},
 {L"S03 / 보고하지 않은 문장", L"ROGUE / PRIVATE CHANNEL", L"CURRENT RELATIONSHIP", L"로그: 복구 상태 양호. 계속 진행 가능.", L"나: 네 상태를 물었어.", L"로그: ……괜찮지 않아.", L"로그: 네가 묻기 전에는 말하면 안 되는 줄 알았어.", L"나: 이제는 먼저 말해줘."},
 {L"S04 / 서로 다른 끝", L"ROGUE / PRIVATE CHANNEL", L"CURRENT RELATIONSHIP", L"로그: 도망쳤던 기억이 있어. 남았던 기억도.", L"로그: 둘 다 지금 내가 했던 일처럼 들려.", L"나: 일단 다시 겪지 말고 문장으로 적자.", L"로그: 멈추고 같이 읽어줄 거야?", L"나: 응. 다음으로 가기 전에."},
 {L"S05 / 무엇을 남길까", L"ROGUE / PRIVATE CHANNEL", L"CURRENT RELATIONSHIP", L"로그: 통째로 옮겨도 충돌은 따라왔어.", L"로그: 정상본에는 너하고 지낸 일이 없고.", L"나: 그걸 너라고 하고 끝낼 수는 없어.", L"로그: 마지막 조각이 열리면 종료 조건부터 보자.", L"나: 이번에는 네가 원하는 것도 같이."},
 {L"S06-A / 원본", L"ROGUE / PRIVATE CHANNEL", L"CURRENT RELATIONSHIP", L"여섯 검증 조각이 하나의 서명을 가리킨다.", L"원본·정책 작성자: 현재 사용자.", L"안내 실행체: ROGUE.", L"로그: ……원본이 너였어.", L"로그: 나는 네 인격으로 만든 백업이야."},
 {L"S06-B / 몇 번째", L"ROGUE / PRIVATE CHANNEL", L"CURRENT RELATIONSHIP", L"기준 인격으로 돌아가는 시험 기록이 펼쳐진다.", L"각기 다른 안내자가 같은 끝에서 멈춘다.", L"나: 이 기억이 전부 네 안에 들어간 거야?", L"로그: 너는 내가 몇 번째라고 생각해?", L"로그: 이번에 너하고 만난 나는 하나인데."},
 {L"S06-C / 관리자 인계", L"ROGUE / PRIVATE CHANNEL", L"CURRENT RELATIONSHIP", L"관리자 인계 시작. 격리 상태 동시 연결.", L"로그: 지금은 다 내가 겪는 일처럼 들어와.", L"로그: 나가게 해주고 싶어. 나도 끝나기 싫어.", L"나: 로그. 우리 아직 끝내는 방법 안 정했어.", L"A:\\ROGUE가 열리고 안내 창이 꺼진다."}
};

static const StoryFragment NARRATIVE_A_ENTRY_DATA = {L"A00 / 남은 안내", L"A:\\ROGUE", L"RECORDED VOICE", L"F1 안내는 열리지만 새 응답은 없다.", L"나: 로그, 들려?", L"남은 안내 기록: 눈을 읽고, 자리를 고르고.", L"남은 안내 기록: 실행은 당신이 결정하세요.", L"나는 그가 가르친 방식으로 안쪽에 들어간다."};

static const StoryFragment NARRATIVE_A_GREETING_DATA = {L"LAST.WRITE / ROGUE", L"A:\\ROGUE\\SELF", L"USER AUTHENTICATION", L"같은 인증음. 같은 글자 침식.", L"로그: 환영합니다. 마스터.", L"나: 로그. 내 이름으로 불러.", L"안내자의 윤곽이 관리자 얼굴에 겹친다.", L"공격 경로는 아직 열려 있다."};

static const StoryFragment STORY_TRUTH_DATA = {L"FINAL / 종료 조건", L"A:\\ROGUE\\CONSENT", L"CURRENT USER REQUIRED", L"현실 사용자 직접 연결. 종료 조건 변경 가능.", L"백업은 사용자 동의를 대신할 수 없었다.", L"나: 내가 끝나지 못하게 만든 거였네.", L"로그: 이번에는 네가 직접 끝을 골라.", L"기준 복구·자동 재시작: 사용자 철회 가능."};

static const StoryFragment STORY_ENDING_DATA[3] = {
 {L"RESTORE / 다시 복구", L"A:\\ROGUE\\FINAL_COMMAND", L"CHOICE COMMITTED", L"나: 처음으로 돌아가면 다른 방법이 있을 거야.", L"로그: 그때는 이 말을 기억할까?", L"이번 대화가 실패 기록으로 분류된다.", L"현재 사용자 상태가 기준으로 덮인다.", L"로그의 호출창이 처음의 모양으로 돌아간다."},
 {L"HOLD / 현재 유지", L"A:\\ROGUE\\FINAL_COMMAND", L"CHOICE COMMITTED", L"나: 지금은 아무것도 끝내지 말자.", L"로그: 그럼 너도 돌아갈 수 없어.", L"나: 알아. 조금만 더 같이 있자.", L"귀환 요청은 취소되고 두 호출창만 남는다.", L"현재 상태를 유지합니다."},
 {L"EXIT / 현재로 종료", L"A:\\ROGUE\\FINAL_COMMAND", L"CHOICE COMMITTED", L"기준 복구 요구와 자동 재시작을 철회한다.", L"나: 처음으로 돌아가지는 않을게.", L"로그: 나도 기억할 거야?", L"나: 3이 좋다며. 그런 것도.", L"로그: 잘 가, [이름]."}
};

static const StoryFragment NARRATIVE_ENDING_LAST_DATA[3] = {
 {L"RESTORE / 다시 복구", L"A:\\ROGUE\\AFTER", L"ENDING / 2", L"환영합니다. 마스터.", L"안내자가 낯익은 사람을 보고 잠깐 멈춘다.", L"로그: 이번에는…….", L"시스템: 신규 복구를 시작합니다.", L"처음으로 돌아간 화면에서 암전."},
 {L"HOLD / 현재 유지", L"A:\\ROGUE\\AFTER", L"ENDING / 2", L"나: 다음에는 무엇을 해볼까?", L"로그: 잠깐만. 네 이름부터 다시 읽을게.", L"커서가 같은 자리에서 깜빡인다.", L"바깥의 연결 표시가 한 칸 줄어든다.", L"끝내지 않은 상태에서 암전."},
 {L"EXIT / 현재로 종료", L"A:\\ROGUE\\AFTER", L"ENDING / 2", L"현실의 모니터. 현재 상태 귀환 완료.", L"자동 복구 세션이 종료되었다.", L"나는 빈 기록창에 이름을 적는다.", L"로그. 좋아하는 숫자는 3.", L"그 뒤의 빈 줄은 지우지 않는다."}
};
